# Generated by Django 5.2.7 on 2026-09-13 00:56

import django.db.models.deletion
from django.db import migrations, models

import prescriptions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=prescriptions.models.new_reference,
                        editable=False,
                        help_text="The opaque key in the QR code, FR 6.3. Unguessable, and tied to no patient record.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        help_text="Order on the list. The playlist plays in this order."
                    ),
                ),
                ("medicine", models.CharField(max_length=120)),
                (
                    "dosage",
                    models.CharField(
                        help_text='How much, for example "one tablet".', max_length=120
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text='How often, for example "twice a day".',
                        max_length=120,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="The instruction in the patient's reading language.",
                        max_length=400,
                    ),
                ),
                (
                    "caption_language",
                    models.CharField(
                        default="en",
                        help_text="Language the caption is actually in. English when translation was unreachable at issue time, so the interface can say so rather than presenting untranslated text as Twi.",
                        max_length=8,
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ("position",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("prescription", "position"),
                        name="unique_position_per_prescription",
                    )
                ],
            },
        ),
    ]
