# Generated by Django 5.2.7 on 2026-09-13 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="caption_provider",
            field=models.CharField(
                default="",
                help_text="Which provider produced the caption, per ADR 011. The stub returns its input unchanged, so without this the interface would present English text as Twi with nothing to distinguish it from a real translation. Stored rather than derived, because the prescription is read back long after the setting may have changed.",
                max_length=32,
            ),
        ),
    ]
