# Generated by Django 5.2.7 on 2026-09-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0002_prescriptionitem_caption_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="A photograph of the medicine, shown to the patient before its dose. Re-encoded on upload to strip camera metadata, which on a phone includes where the photograph was taken.",
                upload_to="medicines/",
            ),
        ),
        migrations.AlterField(
            model_name="prescriptionitem",
            name="medicine",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
