# Generated by Django 5.2.7 on 2026-09-14 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prescriptions", "0003_prescriptionitem_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionitem",
            name="amount",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HALF", "half"),
                    ("1", "one"),
                    ("2", "two"),
                    ("3", "three"),
                    ("4", "four"),
                    ("5", "five"),
                    ("6", "six"),
                    ("7", "seven"),
                    ("8", "eight"),
                    ("9", "nine"),
                    ("10", "ten"),
                ],
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Length of the course, when there is one.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="frequency_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ONCE", "once a day"),
                    ("TWICE", "twice a day"),
                    ("THREE_TIMES", "three times a day"),
                    ("FOUR_TIMES", "four times a day"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="meal",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BEFORE", "before food"),
                    ("AFTER", "after food"),
                    ("WITH", "with food"),
                ],
                help_text="Left empty when it does not matter.",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="times",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="prescriptionitem",
            name="unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TABLET", "tablet"),
                    ("CAPSULE", "capsule"),
                    ("SPOON", "spoon"),
                    ("DROP", "drop"),
                    ("ML", "millilitre"),
                    ("INJECTION", "injection"),
                    ("SACHET", "sachet"),
                ],
                max_length=16,
            ),
        ),
    ]
