// Single place where the API base URL is resolved, so no component ever
// hardcodes a host. In the containerized stack nginx proxies /api to the
// backend, which is why the default is a relative path rather than localhost.
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? "/api";

/**
 * Perform a JSON request against the API.
 *
 * Throws on a non 2xx response so callers handle failure explicitly rather
 * than silently rendering an error body as if it were data, which under
 * hospital connectivity is a realistic and easily missed failure mode.
 */
export async function apiRequest(path, options = {}) {
  // FormData must set its own Content-Type, because the multipart boundary is
  // generated by the browser. Overriding it makes the request unparseable and
  // the server rejects a body that looks perfectly valid from here.
  const isFormData = options.body instanceof FormData;
  const headers = isFormData
    ? { ...options.headers }
    : { "Content-Type": "application/json", ...options.headers };

  const response = await fetch(`${API_BASE_URL}${path}`, {
    ...options,
    headers,
  });

  if (!response.ok) {
    const error = new Error(`API request to ${path} failed with ${response.status}`);
    // Carried on the error, for the callers that must tell one failure from
    // another: a phone reconnecting to a consultation has to know a 410, the
    // doctor ended it, from a 404, the doctor's device is not back yet.
    error.status = response.status;
    throw error;
  }

  // 204 No Content carries no body at all, not even "null". Calling .json()
  // on it throws "Unexpected end of JSON input" despite the request having
  // succeeded, which is the response.ok check above lying to every caller
  // that trusted it. Found wiring up the pairing endpoints, which return 204
  // from every write, since none of them have anything to hand back beyond
  // "done".
  if (response.status === 204) return null;

  return response.json();
}

/** Check that the API and its database are both reachable. */
export function fetchHealth() {
  return apiRequest("/health/");
}
