import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { captionUtterance } from "../api/consultation.js";

/**
 * How a recording reaches the server. The upload's filename and content type
 * are what a speech service uses to decide how to decode the bytes, so a stale
 * extension is not cosmetic, it can make a valid recording unreadable.
 */

let fetchMock;

beforeEach(() => {
  fetchMock = vi.fn().mockResolvedValue({ ok: true, json: async () => ({}) });
  vi.stubGlobal("fetch", fetchMock);
});

afterEach(() => {
  vi.unstubAllGlobals();
  vi.clearAllMocks();
});

function sentBody() {
  return fetchMock.mock.calls[0][1].body;
}

describe("captionUtterance", () => {
  it("sends typed text as JSON", async () => {
    await captionUtterance({ sourceLanguage: "tw", text: "wo tiri" });

    const [, options] = fetchMock.mock.calls[0];
    expect(options.headers["Content-Type"]).toBe("application/json");
    expect(JSON.parse(options.body)).toEqual({
      source_language: "tw",
      text: "wo tiri",
    });
  });

  it("sends a recording as multipart form data", async () => {
    const audio = new Blob(["RIFF"], { type: "audio/wav" });

    await captionUtterance({ sourceLanguage: "en", audio });

    const body = sentBody();
    expect(body).toBeInstanceOf(FormData);
    expect(body.get("source_language")).toBe("en");
  });

  it("never sets its own Content-Type for a recording", async () => {
    // FormData must set the header itself, because the multipart boundary is
    // generated by the browser. Overriding it makes a valid body unparseable.
    const audio = new Blob(["RIFF"], { type: "audio/wav" });

    await captionUtterance({ sourceLanguage: "en", audio });

    const [, options] = fetchMock.mock.calls[0];
    expect(options.headers["Content-Type"]).toBeUndefined();
  });

  it("names a WAV upload with a wav extension", async () => {
    // The recorder converts to WAV before upload. A leftover .webm name would
    // misdescribe the bytes to anything that trusts the filename.
    const audio = new Blob(["RIFF"], { type: "audio/wav" });

    await captionUtterance({ sourceLanguage: "en", audio });

    expect(sentBody().get("audio").name).toBe("utterance.wav");
  });

  it("derives the extension from the recording's own type", async () => {
    const audio = new Blob(["x"], { type: "audio/webm;codecs=opus" });

    await captionUtterance({ sourceLanguage: "en", audio });

    // The codec suffix is stripped, it is still a webm container.
    expect(sentBody().get("audio").name).toBe("utterance.webm");
  });
});
