/**
 * The prescription currently on screen, kept across a page reload.
 *
 * A prescription is the last thing that happens in a consultation and the one
 * screen with something on it the doctor cannot recreate by remembering: a
 * reference, a QR code drawn from it, and whichever medicines have already been
 * entered. Losing it to a reload means issuing a second prescription, which
 * leaves the first one live and scannable with nothing to say it was replaced.
 *
 * Only the reference is stored, not the playlist.
 *
 * That is deliberate and follows ADR 043. The signs are resolved on every read
 * so that a clip a consultant withdraws stops playing everywhere, and a
 * playlist cached in localStorage would be exactly the frozen copy that
 * decision exists to avoid. The reference is refetched on load, which costs one
 * request and cannot go stale.
 *
 * Cleared with the visit, for the reasons in ADR 026. The reference identifies
 * nobody, per ADR 044, but this device is handed from one patient to the next,
 * and the next patient finding the previous patient's medicines on screen is
 * the harm the whole visit lifecycle exists to prevent.
 */

const STORAGE_KEY = "tiemeghana.prescription";

/** Matches the shape the API generates: url safe base64, per ADR 044. */
const REFERENCE = /^[A-Za-z0-9_-]{16,64}$/;

/**
 * Read the prescription that was on screen, or null if there was none.
 *
 * Every access is guarded. localStorage throws in a private window, and an
 * exception here would take down the screen on load, which is strictly worse
 * than losing the reference.
 */
export function loadCurrentPrescription() {
  let raw;
  try {
    raw = localStorage.getItem(STORAGE_KEY);
  } catch {
    return null;
  }

  // Validated rather than trusted. This value is put straight into a request
  // path, and anything that is not a reference cannot be one: the shape is
  // generated by the server and nothing else writes this key.
  return raw && REFERENCE.test(raw) ? raw : null;
}

/** Remember the prescription just issued, so a reload comes back to it. */
export function saveCurrentPrescription(reference) {
  if (!REFERENCE.test(reference ?? "")) return;

  try {
    localStorage.setItem(STORAGE_KEY, reference);
  } catch {
    // Out of quota, or a private window. The prescription is already issued
    // and the QR code is on screen, so the only thing lost is surviving a
    // reload, and failing loudly here would lose the screen as well.
  }
}

/** Forget it. Called when the doctor finishes, and when the visit ends. */
export function clearCurrentPrescription() {
  try {
    localStorage.removeItem(STORAGE_KEY);
  } catch {
    // Nothing to do. A key that cannot be removed was almost certainly never
    // written, since both operations fail for the same reasons.
  }
}
