# Generated by Django 5.2.7 on 2026-09-12 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clips", "0002_alter_signclip_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "english_text",
                    models.CharField(
                        help_text="What the doctor reads when choosing the question.",
                        max_length=200,
                    ),
                ),
                (
                    "twi_text",
                    models.CharField(
                        blank=True,
                        help_text="Optional Twi caption, for a patient who also reads Twi.",
                        max_length=200,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("selection", "Patient taps a sign video answer"),
                            ("yes_no", "Patient nods or shakes, doctor confirms"),
                        ],
                        default="selection",
                        max_length=16,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Groups the bank for the doctor, for example intake or pain.",
                        max_length=60,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Clear this to retire a question without deleting its history.",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Position in the bank. The bank is a clinical checklist.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_clip",
                    models.ForeignKey(
                        help_text="The question signed in GhSL. This is what the patient sees.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="clips.signclip",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "english_text",
                    models.CharField(
                        help_text="What the doctor reads. The patient sees the clip.",
                        max_length=120,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Position in the grid, so the layout is deterministic.",
                    ),
                ),
                (
                    "clip",
                    models.ForeignKey(
                        help_text="The answer signed in GhSL, which is what the patient taps.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answer_options",
                        to="clips.signclip",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        help_text="Deleting the question deletes its options, never orphans them.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="questions.clinicalquestion",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question", "order"), name="unique_option_position"
                    )
                ],
            },
        ),
    ]
