# Generated by Django 5.2.7 on 2026-09-12 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinicalquestion",
            name="prompt_clip",
        ),
        migrations.AlterField(
            model_name="clinicalquestion",
            name="english_text",
            field=models.CharField(
                help_text="What the doctor reads, and the text the GhSL video is stitched from. Prefer words that exist in the clip library.",
                max_length=200,
            ),
        ),
    ]
