# Generated by Django 5.2.7 on 2026-09-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SignClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gloss",
                    models.CharField(
                        help_text="English word label used as the lookup key. Stored uppercase.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("word", "Word sign"),
                            ("letter", "Fingerspelling letter"),
                            ("alert", "Emergency alert"),
                        ],
                        default="word",
                        max_length=16,
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        help_text="Leave empty to record a gloss that still needs filming.",
                        upload_to="clips/",
                    ),
                ),
                (
                    "duration_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Playback length, used to estimate total sequence duration.",
                        null=True,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting consultant review"),
                            ("approved", "Approved for clinical use"),
                            ("rejected", "Rejected, must not be used"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of the GhSL fluent consultant who approved this sign.",
                        max_length=120,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Regional variation, ambiguity, or anything a reviewer flagged.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "GhSL clip",
                "verbose_name_plural": "GhSL clips",
                "ordering": ["gloss"],
            },
        ),
    ]
