# Generated by Django 5.2.7 on 2026-09-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0002_alter_signclip_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClipAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        help_text="The alternative word, stored uppercase. Unique across the whole library, because one word cannot mean two different signs.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "reviewed_by",
                    models.CharField(
                        blank=True,
                        help_text="The GhSL fluent consultant who confirmed this word and the sign mean the same thing clinically. Leave empty and the alias is ignored.",
                        max_length=120,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Why these are interchangeable, or any caveat.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clip",
                    models.ForeignKey(
                        help_text="The sign this word also means.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="clips.signclip",
                    ),
                ),
            ],
            options={
                "verbose_name": "clip alias",
                "verbose_name_plural": "clip aliases",
                "ordering": ["term"],
            },
        ),
    ]
