# Generated by Django 5.2.7 on 2026-09-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0003_clipalias"),
    ]

    operations = [
        migrations.AddField(
            model_name="signclip",
            name="source_checksum",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Hash of the imported file. Lets a repeated import recognise unchanged footage and leave its approval alone.",
                max_length=64,
            ),
        ),
    ]
