# Generated by Django 5.2.7 on 2026-09-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0004_signclip_source_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signclip",
            name="kind",
            field=models.CharField(
                choices=[
                    ("word", "Word sign"),
                    ("phrase", "Phrase sign"),
                    ("letter", "Fingerspelling letter"),
                    ("alert", "Emergency alert"),
                    ("prompt", "System prompt"),
                ],
                default="word",
                max_length=16,
            ),
        ),
    ]
