# Generated by Django 5.2.7 on 2026-09-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clips", "0006_normalize_glosses"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="signclip",
            index=models.Index(
                condition=models.Q(
                    ("review_status", "approved"),
                    models.Q(("video", ""), _negated=True),
                ),
                fields=["kind", "gloss"],
                name="clip_resolvable_by_kind",
            ),
        ),
    ]
